# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Akritas <- function(truth, unique_times, FX_train, FX_predict, newdata, lambda) {
    .Call(`_mlr3learners_proba_C_Akritas`, truth, unique_times, FX_train, FX_predict, newdata, lambda)
}

